variable "region" { default = "us-east-1" }
variable "vpc_cidr" { default = "10.0.0.0/16" }
variable "public_cidrs" { default = ["10.0.1.0/24", "10.0.2.0/24"] }    # one per AZ
variable "private_cidrs" { default = ["10.0.11.0/24", "10.0.12.0/24"] } # one per AZ
variable "instance_type" { default = "t3.micro" }
variable "asg_min" { default = 2 }
variable "asg_max" { default = 6 }
variable "asg_desired" { default = 2 }
variable "http_port" { default = 80 }
variable "key_name" { default = "" } # optional ssh key
